'use client'

import { useState, useEffect, useRef, useCallback } from 'react'
import { useSession, signOut } from 'next-auth/react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import JSZip from 'jszip'
import Editor from '@monaco-editor/react'
import { GenerationPlan, GenerationStep, ModificationDetail} from '../../lib/anthropic'
import { generateProject } from '../../lib/generate-client'

interface Message {
  role: 'user' | 'assistant'
  content: string
  id: string
  timestamp: Date
}

interface ProjectFile {
  path: string
  content: string
  type?: string
}

export default function EditorPage() {
  const { data: session, status } = useSession()
  const router = useRouter()
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [generatedCode, setGeneratedCode] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [generationPlan, setGenerationPlan] = useState<GenerationPlan | null>(null)
  const [, setSteps] = useState<GenerationStep[]>([])
  const [, setSubSteps] = useState<Array<{step: string, status: string, description: string, progress: number}>>([])
  const [, setModifications] = useState<ModificationDetail[]>([])
  const [error, setError] = useState('')
  const [, setHasAutoGenerated] = useState(false)
  const [, setCurrentGenerationMessageId] = useState<string | null>(null)
  const [, setShowStuckMessage] = useState(false)
  const [projectId, setProjectId] = useState<string | null>(null)
  const [projectName, setProjectName] = useState<string>('')
  const [isSaving, setIsSaving] = useState(false)
  const [lastSaved, setLastSaved] = useState<Date | null>(null)
  const [isMultiFile, setIsMultiFile] = useState(false)
  const [projectFiles, setProjectFiles] = useState<Array<{path: string, content: string, type?: string}>>([])
  const [hasDatabase, setHasDatabase] = useState(false)
  const [databaseSchema, setDatabaseSchema] = useState<string | null>(null)
  const [dbBranchId, setDbBranchId] = useState<string | null>(null)
  const [dbConnectionString, setDbConnectionString] = useState<string | null>(null)
  const [githubRepo, setGithubRepo] = useState<string | null>(null)
  const [githubRepoFullName, setGithubRepoFullName] = useState<string | null>(null)
  const [githubCloneUrl, setGithubCloneUrl] = useState<string | null>(null)
  const [activeView, setActiveView] = useState<'preview' | 'code'>('preview')
  const [selectedFile, setSelectedFile] = useState<string | null>(null)
  const [fileContent, setFileContent] = useState<string>('')
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set(['src', 'public']))
  const [deviceView, setDeviceView] = useState<'desktop' | 'tablet' | 'mobile'>('desktop')

  // Build server states
  const [buildJobId, setBuildJobId] = useState<string | null>(null)
  const [buildUrl, setBuildUrl] = useState<string | null>(null)
  const [buildStatus, setBuildStatus] = useState<'idle' | 'queued' | 'building' | 'completed' | 'failed'>('idle')

  const messagesEndRef = useRef<HTMLDivElement>(null)
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const [collapsedSections, setCollapsedSections] = useState<Set<string>>(new Set())
  const stepsEndRef = useRef<HTMLDivElement>(null)
  const hasInitialized = useRef(false)
  const lastProgressUpdateTime = useRef<number>(Date.now())
  const stuckMessageTimer = useRef<NodeJS.Timeout | null>(null)
  const hasSavedGeneration = useRef(false)

  // Redirection si non authentifié
  useEffect(() => {
    if (status === 'unauthenticated') {
      const urlParams = new URLSearchParams(window.location.search)
      const promptFromUrl = urlParams.get('prompt')

      if (promptFromUrl) {
        const callbackUrl = `/editor?prompt=${encodeURIComponent(promptFromUrl)}`
        router.push(`/auth/signin?callbackUrl=${encodeURIComponent(callbackUrl)}`)
      } else {
        router.push('/auth/signin?callbackUrl=/editor')
      }
    }
  }, [status, router])

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  // Fonction pour sauvegarder le projet
  const saveProject = useCallback(async (code: string, prompt: string) => {
    if ((!code && !isMultiFile) || !prompt || !session?.user?.email) return

    try {
      setIsSaving(true)
      const userId = (session.user as any)?.id || session.user.email
      const isTemporaryId = projectId?.startsWith('proj-')

      if (!projectId || isTemporaryId) {
        const name = projectName || `Projet ${new Date().toLocaleDateString()}`
        const requestBody: any = { userId, name, prompt }

        if (isMultiFile) {
          requestBody.files = projectFiles
          requestBody.framework = 'react'
          requestBody.hasDatabase = hasDatabase
          requestBody.databaseSchema = databaseSchema
        } else {
          requestBody.code = code
        }

        const response = await fetch('/api/projects', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(requestBody),
        })

        if (response.ok) {
          const { project } = await response.json()
          setProjectId(project.id)
          setProjectName(project.name)
          setLastSaved(new Date())
          window.history.pushState({}, '', `/editor?projectId=${project.id}`)
        }
      } else {
        const requestBody: any = { projectId, status: 'ready' }

        if (isMultiFile) {
          requestBody.files = projectFiles
          requestBody.hasDatabase = hasDatabase
          requestBody.databaseSchema = databaseSchema
          if (dbBranchId) requestBody.dbBranchId = dbBranchId
          if (dbConnectionString) requestBody.dbConnectionString = dbConnectionString
          if (githubRepo) requestBody.githubRepo = githubRepo
          if (githubRepoFullName) requestBody.githubRepoFullName = githubRepoFullName
          if (githubCloneUrl) requestBody.githubCloneUrl = githubCloneUrl
        } else {
          requestBody.code = code
        }

        const response = await fetch('/api/projects', {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(requestBody),
        })

        if (response.ok) {
          setLastSaved(new Date())
        }
      }
    } catch (error) {
      console.error('Erreur lors de la sauvegarde:', error)
    } finally {
      setIsSaving(false)
    }
  }, [projectId, projectName, session, isMultiFile, projectFiles, hasDatabase, databaseSchema, dbBranchId, dbConnectionString])

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  useEffect(() => {
    if (!isMultiFile && generatedCode && messages.length > 0) {
      const lastUserMessage = messages.filter(m => m.role === 'user').slice(-1)[0]
      if (lastUserMessage) {
        saveProject(generatedCode, lastUserMessage.content)
      }
    }
  }, [generatedCode, messages, saveProject, isMultiFile])

  useEffect(() => {
    if (!isGenerating && isMultiFile && projectFiles.length > 0 && messages.length > 0 && !hasSavedGeneration.current) {
      const lastUserMessage = messages.filter(m => m.role === 'user').slice(-1)[0]
      if (lastUserMessage) {
        saveProject('', lastUserMessage.content)
        hasSavedGeneration.current = true
      }
    }
  }, [isGenerating, projectFiles, messages, saveProject, isMultiFile, projectId])

  const downloadProject = useCallback(async () => {
    if (projectFiles.length === 0) {
      alert('Aucun fichier à télécharger')
      return
    }

    try {
      const zip = new JSZip()
      projectFiles.forEach(file => {
        const cleanPath = file.path.startsWith('/') ? file.path.slice(1) : file.path
        zip.file(cleanPath, file.content)
      })

      const readme = `# ${projectName || 'Projet React'}\n\nGénéré par Wapify\n\n## Installation\n\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Développement\n\n\`\`\`bash\nnpm run dev\n\`\`\``
      zip.file('README.md', readme)

      const blob = await zip.generateAsync({ type: 'blob' })
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `${projectName || 'projet'}-${Date.now()}.zip`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
    } catch (error) {
      console.error('Erreur lors de la création du ZIP:', error)
      alert('Erreur lors de la création du fichier ZIP')
    }
  }, [projectFiles, projectName])

  useEffect(() => {
    if (stepsEndRef.current && isGenerating) {
      const timer = setTimeout(() => {
        stepsEndRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' })
      }, 100)
      return () => clearTimeout(timer)
    }
  }, [isGenerating])

  useEffect(() => {
    if (hasInitialized.current) return
    hasInitialized.current = true

    if (typeof window !== 'undefined') {
      const urlParams = new URLSearchParams(window.location.search)
      const projectIdFromUrl = urlParams.get('projectId')
      const promptFromUrl = urlParams.get('prompt')
      const styleFromUrl = urlParams.get('style')

      if (projectIdFromUrl) {
        loadProject(projectIdFromUrl)
      } else if (promptFromUrl && promptFromUrl.trim()) {
        setHasAutoGenerated(true)

        let finalPrompt = promptFromUrl
        if (styleFromUrl) {
          const styleInstructions: Record<string, string> = {
            modern: "Use a modern minimalist design with generous whitespace, clean sans-serif typography, subtle animations, and a neutral color palette with accent colors.",
            gradient: "Use bold gradient backgrounds with vibrant colors, smooth color transitions, animated elements with hover effects, and modern glassmorphism with blur effects.",
            dark: "Use a dark mode design with dark backgrounds, neon accent colors for CTAs, high contrast for readability, and strategic highlights.",
            brutalist: "Use a brutalist design with heavy black borders, bold geometric shapes, strong typography hierarchy, and high contrast black and white colors.",
            glassmorphism: "Use glassmorphism design with frosted glass blur effects on cards, soft drop shadows, translucent backgrounds with vibrant colors, and depth layers."
          }
          const instructions = styleInstructions[styleFromUrl]
          if (instructions) {
            finalPrompt = `${promptFromUrl} ${instructions}`
          }
        }

        handleGenerateWithPrompt(finalPrompt)
        window.history.replaceState({}, '', '/editor')
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const loadProject = async (id: string) => {
    try {
      const response = await fetch(`/api/projects/${id}`)
      if (!response.ok) {
        throw new Error('Projet introuvable')
      }

      const data = await response.json()
      const project = data.project

      setProjectId(project.id)
      setProjectName(project.name)

      if (project.framework === 'react') {
        setIsMultiFile(true)
        setHasDatabase(project.has_database || false)

        if (data.files && Array.isArray(data.files) && data.files.length > 0) {
          setProjectFiles(data.files)
          setGeneratedCode('multi-file-project')
          if (data.files.length > 0) {
            setSelectedFile(data.files[0].path)
          }
        } else {
          setError('Ce projet React n\'a aucun fichier sauvegardé')
          setProjectFiles([])
          setGeneratedCode('')
        }
      } else if (project.code) {
        setIsMultiFile(false)
        setGeneratedCode(project.code)
      }

      const initialMessage: Message = {
        role: 'user',
        content: project.prompt,
        id: `msg-${Date.now()}`,
        timestamp: new Date(project.created_at)
      }
      setMessages([initialMessage])
    } catch (err) {
      setError('Impossible de charger ce projet')
      console.error('Error loading project:', err)
    }
  }

  const handleGenerateWithPrompt = useCallback(async (promptText: string) => {
    if (!promptText.trim() || isGenerating) return

    const messageId = `msg-${Date.now()}`
    const userMessage: Message = {
      role: 'user',
      content: promptText,
      id: messageId,
      timestamp: new Date()
    }
    setMessages(prev => [...prev, userMessage])
    setCurrentGenerationMessageId(messageId)
    setInput('')
    setIsGenerating(true)
    setError('')
    setSteps([])
    setSubSteps([])
    setGenerationPlan(null)
    setModifications([])
    hasSavedGeneration.current = false

    try {
      const currentProjectId = projectId || `proj-${Date.now()}-${Math.random().toString(36).substring(7)}`
      if (!projectId) {
        setProjectId(currentProjectId)
      }

      const result = await generateProject({
        prompt: promptText,
        conversationHistory: messages,
        projectId: currentProjectId,
        userId: (session?.user as any)?.id || session?.user?.email,
        onProgress: (progress) => {
          console.log(`Generation progress: ${progress}%`)
        },
        onEvent: (event) => {
          if (event.type === 'plan') {
            setGenerationPlan(event.data)
          } else if (event.type === 'modifications') {
            setModifications(event.data)
          } else if (event.type === 'chat_message') {
            const chatMessage: Message = {
              role: 'assistant',
              content: event.data,
              id: `msg-gen-${Date.now()}-${Math.random()}`,
              timestamp: new Date()
            }
            setMessages(prev => [...prev, chatMessage])
          } else if (event.type === 'step') {
            setSteps(prev => {
              const existingIndex = prev.findIndex(s => s.step === event.data.step)
              if (existingIndex >= 0) {
                const newSteps = [...prev]
                newSteps[existingIndex] = event.data
                return newSteps
              }
              return [...prev, event.data]
            })
          } else if (event.type === 'substep') {
            lastProgressUpdateTime.current = Date.now()
            setShowStuckMessage(false)
            if (stuckMessageTimer.current) {
              clearTimeout(stuckMessageTimer.current)
            }
            stuckMessageTimer.current = setTimeout(() => {
              setShowStuckMessage(true)
            }, 5000)
            setSubSteps(prev => {
              const existingIndex = prev.findIndex(s => s.step === event.data.step)
              if (existingIndex >= 0) {
                const newSubSteps = [...prev]
                newSubSteps[existingIndex] = event.data
                return newSubSteps
              }
              return [...prev, event.data]
            })
          }
        }
      })

      if (result.isMultiFile) {
        setIsMultiFile(true)
        setProjectFiles(result.files)
        setHasDatabase(result.hasDatabase || false)
        setDatabaseSchema(result.databaseSchema || null)
        if (result.dbBranchId) {
          setDbBranchId(result.dbBranchId)
        }
        if (result.dbConnectionString) {
          setDbConnectionString(result.dbConnectionString)
        }
        if (result.githubRepo) {
          setGithubRepo(result.githubRepo)
          setGithubRepoFullName(result.githubRepoFullName || null)
          setGithubCloneUrl(result.githubCloneUrl || null)
        }

        const defaultFile = result.files.find((f: any) =>
          f.path === 'src/App.jsx' || f.path === 'src/App.tsx' || f.path === 'src/main.jsx'
        ) || result.files[0]

        if (defaultFile) {
          setSelectedFile(defaultFile.path)
          setGeneratedCode(defaultFile.content)
        }
      } else {
        setIsMultiFile(false)
        setGeneratedCode(result.files[0]?.content || '')
      }

      const assistantMessage: Message = {
        role: 'assistant',
        content: 'Application générée avec succès ! Vous pouvez la voir dans la preview et demander des modifications.',
        id: `msg-${Date.now()}`,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, assistantMessage])

    } catch (err) {
      console.error('Generation error:', err)
      setError(err instanceof Error ? err.message : 'Erreur de génération')

      const errorMessage: Message = {
        role: 'assistant',
        content: `❌ Erreur: ${err instanceof Error ? err.message : 'Erreur de génération'}`,
        id: `msg-${Date.now()}`,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, errorMessage])
    } finally {
      setIsGenerating(false)
      setShowStuckMessage(false)
      if (stuckMessageTimer.current) {
        clearTimeout(stuckMessageTimer.current)
        stuckMessageTimer.current = null
      }
    }
  }, [isGenerating, messages, generationPlan])

  const handleGenerate = async () => {
    if (!input.trim() || isGenerating) return
    await handleGenerateWithPrompt(input)
  }

  const triggerBuild = async (files: Array<{path: string, content: string}>, projId: string) => {
    try {
      setBuildStatus('queued')

      const buildMessage: Message = {
        role: 'assistant',
        content: '🔨 Compilation avec Vite...',
        id: `msg-build-${Date.now()}`,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, buildMessage])

      const response = await fetch('/api/build', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          projectId: projId || `temp-${Date.now()}`,
          files,
          projectName: projectName || 'Wapify App'
        })
      })

      if (!response.ok) {
        throw new Error('Failed to trigger build')
      }

      const data = await response.json()
      setBuildJobId(data.jobId)
      setBuildStatus('building')
    } catch (error) {
      console.error('Error triggering build:', error)
      setBuildStatus('failed')
      setError('Échec du démarrage du build')

      const errorMessage: Message = {
        role: 'assistant',
        content: '❌ Erreur lors de la compilation',
        id: `msg-build-error-${Date.now()}`,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, errorMessage])
    }
  }

  const rebuildProject = async (projId: string) => {
    try {
      setBuildStatus('queued')
      setError('')

      const response = await fetch(`/api/projects/${projId}/rebuild`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' }
      })

      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || 'Failed to rebuild project')
      }

      const data = await response.json()
      setBuildJobId(data.jobId)
      setBuildStatus('building')
    } catch (error) {
      console.error('Error rebuilding project:', error)
      setBuildStatus('failed')
      setError(error instanceof Error ? error.message : 'Échec du rebuild')
    }
  }

  const convertToProxyUrl = (blobUrl: string): string => {
    try {
      const url = new URL(blobUrl)
      const pathParts = url.pathname.split('/').filter(Boolean)
      if (pathParts.length >= 3) {
        return `/api/preview/${pathParts.join('/')}`
      }
    } catch (e) {
      console.error('Failed to convert URL:', e)
    }
    return blobUrl
  }

  const handleBuildComplete = (url: string) => {
    const proxyUrl = convertToProxyUrl(url)
    setBuildUrl(proxyUrl)
    setBuildStatus('completed')

    const successMessage: Message = {
      role: 'assistant',
      content: '✅ Build réussi ! Votre application est prête.',
      id: `msg-build-success-${Date.now()}`,
      timestamp: new Date()
    }
    setMessages(prev => [...prev, successMessage])
  }

  const handleBuildError = (error: string) => {
    console.error('Build failed:', error)
    setBuildStatus('failed')
    setError(`Erreur de build: ${error}`)

    const errorMessage: Message = {
      role: 'assistant',
      content: `❌ Erreur de build: ${error}`,
      id: `msg-build-error-${Date.now()}`,
      timestamp: new Date()
    }
    setMessages(prev => [...prev, errorMessage])
  }

  useEffect(() => {
    if (isMultiFile && projectFiles.length > 0 && buildStatus === 'idle') {
      const currentProjectId = projectId || `temp-${Date.now()}`
      triggerBuild(projectFiles, currentProjectId)
    }
  }, [projectFiles, isMultiFile, buildStatus, projectId])

  useEffect(() => {
    if (buildStatus === 'building' && buildJobId) {
      const pollInterval = setInterval(async () => {
        try {
          const response = await fetch(`/api/build?jobId=${buildJobId}`)
          if (response.ok) {
            const data = await response.json()

            if (data.status === 'completed' && data.url) {
              handleBuildComplete(data.url)
              clearInterval(pollInterval)
            } else if (data.status === 'failed') {
              handleBuildError(data.error || 'Build failed')
              clearInterval(pollInterval)
            }
          }
        } catch (error) {
          console.error('Error polling build status:', error)
        }
      }, 2000)

      return () => clearInterval(pollInterval)
    }
  }, [buildStatus, buildJobId, handleBuildComplete, handleBuildError])

  const handleModification = async () => {
    if (!input.trim() || isGenerating || !generatedCode) return

    const messageId = `msg-${Date.now()}`
    const userMessage: Message = {
      role: 'user',
      content: input,
      id: messageId,
      timestamp: new Date()
    }
    setMessages(prev => [...prev, userMessage])
    setCurrentGenerationMessageId(messageId)
    setInput('')
    setIsGenerating(true)
    setError('')
    setSteps([])
    setModifications([])

    try {
      const requestBody: any = {
        modification: userMessage.content,
        conversationHistory: messages,
        isMultiFile
      }

      if (isMultiFile) {
        requestBody.projectFiles = projectFiles
      } else {
        requestBody.currentCode = generatedCode
      }

      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody)
      })

      if (!response.ok) {
        throw new Error('Erreur de modification')
      }

      const reader = response.body?.getReader()
      const decoder = new TextDecoder()

      if (!reader) {
        throw new Error('Pas de stream disponible')
      }

      let buffer = ''

      while (true) {
        const { done, value } = await reader.read()

        if (done) break

        buffer += decoder.decode(value, { stream: true })
        const lines = buffer.split('\n\n')
        buffer = lines.pop() || ''

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            const data = line.slice(6)
            try {
              const event = JSON.parse(data)

              if (event.type === 'step') {
                setSteps(prev => {
                  const existingIndex = prev.findIndex(s => s.step === event.data.step)
                  if (existingIndex >= 0) {
                    const newSteps = [...prev]
                    newSteps[existingIndex] = event.data
                    return newSteps
                  }
                  return [...prev, event.data]
                })
              } else if (event.type === 'complete') {
                if (event.data.isMultiFile && event.data.files) {
                  setProjectFiles(event.data.files)

                  const mainFile = event.data.files.find((f: any) =>
                    f.path === 'src/App.jsx' || f.path === 'src/main.jsx'
                  ) || event.data.files[0]

                  if (mainFile) {
                    setGeneratedCode(mainFile.content)
                  }
                } else if (event.data.code) {
                  setGeneratedCode(event.data.code)
                }

                const assistantMessage: Message = {
                  role: 'assistant',
                  content: '✨ Modification appliquée avec succès !',
                  id: `msg-${Date.now()}`,
                  timestamp: new Date()
                }
                setMessages(prev => [...prev, assistantMessage])
              } else if (event.type === 'error') {
                throw new Error(event.data.message)
              }
            } catch (e) {
              console.error('Erreur lors du parsing de l\'événement:', e)
            }
          }
        }
      }
    } catch (err) {
      console.error('Erreur lors de la modification:', err)
      setError(err instanceof Error ? err.message : 'Erreur de modification')

      const errorMessage: Message = {
        role: 'assistant',
        content: `❌ Erreur: ${err instanceof Error ? err.message : 'Erreur de modification'}`,
        id: `msg-${Date.now()}`,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, errorMessage])
    } finally {
      setIsGenerating(false)
    }
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    if (!generatedCode) {
      handleGenerate()
    } else {
      handleModification()
    }
  }

  const downloadCode = () => {
    const blob = new Blob([generatedCode], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `wapify-app-${Date.now()}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const resetProject = () => {
    setMessages([])
    setGeneratedCode('')
    setGenerationPlan(null)
    setSteps([])
    setError('')
  }

  useEffect(() => {
    console.log(`projectFiles state changed:`, {
      length: projectFiles.length,
      isMultiFile,
      generatedCode: generatedCode ? 'exists' : 'null',
      files: projectFiles.map(f => f.path)
    })
  }, [projectFiles, isMultiFile, generatedCode])

  if (status === 'loading') {
    return (
      <div className="min-h-screen bg-wapify-bg flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-wapify-accent border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-wapify-text-secondary">Chargement...</p>
        </div>
      </div>
    )
  }

  // File tree helpers
  interface FileNode {
    name: string
    path: string
    type: 'file' | 'folder'
    children?: FileNode[]
    content?: string
  }

  const buildFileTree = (files: Array<{path: string, content: string}>): FileNode[] => {
    const root: FileNode[] = []

    files.forEach(file => {
      const parts = file.path.split('/')
      let currentLevel = root

      parts.forEach((part, index) => {
        const isFile = index === parts.length - 1
        const existingNode = currentLevel.find(node => node.name === part)

        if (existingNode) {
          if (!isFile && existingNode.children) {
            currentLevel = existingNode.children
          }
        } else {
          const newNode: FileNode = {
            name: part,
            path: parts.slice(0, index + 1).join('/'),
            type: isFile ? 'file' : 'folder',
            children: isFile ? undefined : [],
            content: isFile ? file.content : undefined
          }
          currentLevel.push(newNode)
          if (!isFile && newNode.children) {
            currentLevel = newNode.children
          }
        }
      })
    })

    return root
  }

  const toggleFolder = (folderPath: string) => {
    setExpandedFolders(prev => {
      const newSet = new Set(prev)
      if (newSet.has(folderPath)) {
        newSet.delete(folderPath)
      } else {
        newSet.add(folderPath)
      }
      return newSet
    })
  }

  const getFileIcon = (fileName: string) => {
    if (fileName.endsWith('.tsx') || fileName.endsWith('.ts')) return '📘'
    if (fileName.endsWith('.jsx') || fileName.endsWith('.js')) return '📜'
    if (fileName.endsWith('.css')) return '🎨'
    if (fileName.endsWith('.json')) return '📋'
    if (fileName.endsWith('.html')) return '🌐'
    return '📄'
  }

  const renderFileTree = (nodes: FileNode[], depth: number = 0): React.ReactElement[] => {
    return nodes.map((node) => {
      if (node.type === 'folder') {
        const isExpanded = expandedFolders.has(node.path)
        return (
          <div key={node.path}>
            <button
              onClick={() => toggleFolder(node.path)}
              className="w-full text-left px-2 py-1 text-sm transition flex items-center hover:bg-wapify-accent/10"
              style={{ paddingLeft: `${depth * 12 + 8}px` }}
            >
              <span className="mr-1 text-xs text-wapify-text-secondary">
                {isExpanded ? '▼' : '▶'}
              </span>
              <span className="mr-2">
                {isExpanded ? '📂' : '📁'}
              </span>
              <span className="text-wapify-text">{node.name}</span>
            </button>
            {isExpanded && node.children && (
              <div>{renderFileTree(node.children, depth + 1)}</div>
            )}
          </div>
        )
      } else {
        const isSelected = selectedFile === node.path
        return (
          <button
            key={node.path}
            onClick={() => {
              setSelectedFile(node.path)
              setFileContent(node.content || '')
            }}
            className={`w-full text-left px-2 py-1 text-sm transition flex items-center ${
              isSelected ? 'bg-wapify-accent/20 text-wapify-text' : 'text-wapify-text-secondary hover:bg-wapify-accent/10 hover:text-wapify-text'
            }`}
            style={{ paddingLeft: `${depth * 12 + 24}px` }}
          >
            <span className="mr-2">{getFileIcon(node.name)}</span>
            {node.name}
          </button>
        )
      }
    })
  }

  if (!session) {
    return null
  }

  return (
    <div className="h-screen flex flex-col bg-wapify-bg">
      <div className="grain-texture"></div>

      {/* Top Navigation */}
      <nav className="h-16 bg-wapify-panel border-b-2 border-wapify-border flex items-center justify-between px-6 flex-shrink-0 relative z-10">
        <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition">
          <div className="w-9 h-9 bg-gradient-to-br from-wapify-accent to-wapify-accent-dark rounded-xl flex items-center justify-center text-lg shadow-lg">
            ⚡
          </div>
          <span className="text-xl font-bold text-wapify-text">Wapify</span>
        </Link>

        <div className="flex items-center gap-3">
          {lastSaved && (
            <div className="text-sm text-wapify-text-secondary flex items-center gap-2">
              {isSaving ? (
                <>
                  <div className="w-2 h-2 bg-wapify-accent rounded-full animate-pulse"></div>
                  <span>Sauvegarde...</span>
                </>
              ) : (
                <>
                  <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                  <span>Sauvegardé {lastSaved.toLocaleTimeString()}</span>
                </>
              )}
            </div>
          )}

          {generatedCode && (
            <>
              <button
                onClick={isMultiFile ? downloadProject : downloadCode}
                className="px-4 py-2 bg-wapify-accent text-white rounded-xl font-semibold hover:bg-wapify-accent-dark transition shadow-md text-sm"
              >
                📥 Télécharger
              </button>
              <button
                onClick={resetProject}
                className="px-4 py-2 bg-wapify-border text-wapify-text rounded-xl font-semibold hover:bg-wapify-accent/10 transition text-sm"
              >
                Nouveau
              </button>
            </>
          )}

          <Link
            href="/dashboard"
            className="px-4 py-2 bg-wapify-border text-wapify-text rounded-xl font-semibold hover:bg-wapify-accent/20 transition text-sm"
          >
            Mes Projets
          </Link>

          <div className="text-sm text-wapify-text-secondary">
            {session?.user?.email}
          </div>

          <button
            onClick={() => signOut({ callbackUrl: '/' })}
            className="px-4 py-2 bg-wapify-border text-wapify-text rounded-xl font-semibold hover:bg-red-100 transition text-sm"
          >
            Déconnexion
          </button>
        </div>
      </nav>

      {/* Main Split-Pane Layout */}
      <div className="flex-1 flex overflow-hidden relative z-0">
        {/* Left Panel - Chat Interface */}
        <div className="w-96 bg-wapify-panel border-r-2 border-wapify-border flex flex-col relative z-0">
          {/* Chat Header */}
          <div className="p-4 border-b-2 border-wapify-border flex-shrink-0">
            <div className="flex items-center gap-2 mb-2">
              <div className="w-8 h-8 bg-wapify-accent/10 rounded-lg flex items-center justify-center text-lg">
                💬
              </div>
              <h2 className="text-lg font-bold text-wapify-text">Conversation</h2>
            </div>
            <p className="text-xs text-wapify-text-secondary">
              {!generatedCode ? 'Décrivez l\'application à créer' : 'Demandez des modifications'}
            </p>
          </div>

          {/* Messages Area */}
          <div className="flex-1 overflow-y-auto p-4 space-y-3">
            {messages.length === 0 && (
              <div className="text-center py-12">
                <div className="text-5xl mb-4 opacity-50">✨</div>
                <p className="text-sm text-wapify-text-secondary">
                  Commencez par décrire votre app
                </p>
              </div>
            )}

            {messages.map((msg, idx) => (
              <div
                key={idx}
                className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} animate-fadeIn`}
              >
                <div
                  className={`max-w-[85%] rounded-xl p-3 shadow-sm ${
                    msg.role === 'user'
                      ? 'bg-wapify-accent text-white'
                      : 'bg-white border-2 border-wapify-border text-wapify-text'
                  }`}
                >
                  <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                  <p className="text-[10px] mt-1 opacity-60">{msg.timestamp.toLocaleTimeString()}</p>
                </div>
              </div>
            ))}

            {isGenerating && (
              <div className="flex justify-start">
                <div className="bg-white border-2 border-wapify-border rounded-xl p-3">
                  <div className="flex items-center gap-2">
                    <div className="w-2 h-2 bg-wapify-accent rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                    <div className="w-2 h-2 bg-wapify-accent rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                    <div className="w-2 h-2 bg-wapify-accent rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
                  </div>
                </div>
              </div>
            )}

            <div ref={messagesEndRef} />
          </div>

          {/* Input Area */}
          <div className="p-4 border-t-2 border-wapify-border flex-shrink-0 bg-wapify-bg">
            <form onSubmit={handleSubmit} className="space-y-2">
              <textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault()
                    handleSubmit(e)
                  }
                }}
                placeholder={!generatedCode ? "Décrivez votre application..." : "Demandez une modification..."}
                className="w-full px-3 py-2 bg-white border-2 border-wapify-border rounded-xl text-wapify-text placeholder-wapify-text-secondary focus:border-wapify-accent focus:outline-none text-sm resize-none"
                disabled={isGenerating}
                rows={3}
              />
              <button
                type="submit"
                disabled={isGenerating || !input.trim()}
                className="w-full px-4 py-2 bg-wapify-accent text-white rounded-xl font-semibold hover:bg-wapify-accent-dark transition shadow-md disabled:opacity-50 disabled:cursor-not-allowed text-sm"
              >
                {isGenerating ? '⏳ Génération...' : '✨ Envoyer'}
              </button>
            </form>
          </div>
        </div>

        {/* Right Panel - Preview & Code */}
        <div className="flex-1 flex flex-col bg-wapify-bg relative z-0">
          {/* Top Bar with Tabs */}
          <div className="bg-wapify-panel border-b-2 border-wapify-border flex items-center justify-between px-4 flex-shrink-0">
            <div className="flex items-center gap-2">
              <button
                onClick={() => setActiveView('preview')}
                className={`px-4 py-3 font-semibold transition text-sm ${
                  activeView === 'preview'
                    ? 'text-wapify-accent border-b-2 border-wapify-accent'
                    : 'text-wapify-text-secondary hover:text-wapify-text'
                }`}
              >
                👁️ Preview
              </button>
              {isMultiFile && (
                <button
                  onClick={() => setActiveView('code')}
                  className={`px-4 py-3 font-semibold transition text-sm ${
                    activeView === 'code'
                      ? 'text-wapify-accent border-b-2 border-wapify-accent'
                      : 'text-wapify-text-secondary hover:text-wapify-text'
                  }`}
                >
                  💻 Code
                </button>
              )}
            </div>

            {activeView === 'preview' && generatedCode && (
              <div className="flex items-center gap-2">
                {/* Device Toggle */}
                <div className="flex items-center gap-1 bg-wapify-bg border-2 border-wapify-border rounded-lg p-1">
                  <button
                    onClick={() => setDeviceView('desktop')}
                    className={`p-1.5 rounded transition ${
                      deviceView === 'desktop' ? 'bg-wapify-accent text-white' : 'text-wapify-text-secondary hover:text-wapify-text'
                    }`}
                    title="Desktop"
                  >
                    <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M3 4a1 1 0 011-1h12a1 1 0 011 1v8a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 14h14v1a1 1 0 01-1 1H4a1 1 0 01-1-1v-1z" />
                    </svg>
                  </button>
                  <button
                    onClick={() => setDeviceView('tablet')}
                    className={`p-1.5 rounded transition ${
                      deviceView === 'tablet' ? 'bg-wapify-accent text-white' : 'text-wapify-text-secondary hover:text-wapify-text'
                    }`}
                    title="Tablet"
                  >
                    <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M6 3a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V5a2 2 0 00-2-2H6zm4 12a1 1 0 100-2 1 1 0 000 2z" />
                    </svg>
                  </button>
                  <button
                    onClick={() => setDeviceView('mobile')}
                    className={`p-1.5 rounded transition ${
                      deviceView === 'mobile' ? 'bg-wapify-accent text-white' : 'text-wapify-text-secondary hover:text-wapify-text'
                    }`}
                    title="Mobile"
                  >
                    <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M7 3a2 2 0 00-2 2v10a2 2 0 002 2h6a2 2 0 002-2V5a2 2 0 00-2-2H7zm3 12a1 1 0 100-2 1 1 0 000 2z" />
                    </svg>
                  </button>
                </div>

                <button
                  onClick={() => {
                    if (buildUrl) {
                      window.open(buildUrl, '_blank')
                    }
                  }}
                  disabled={!buildUrl}
                  className="px-3 py-1.5 bg-wapify-accent text-white rounded-lg font-semibold hover:bg-wapify-accent-dark transition shadow-md disabled:opacity-50 text-sm"
                >
                  🚀 Publier
                </button>
              </div>
            )}
          </div>

          {/* Content Area */}
          <div className="flex-1 relative overflow-hidden">
            {activeView === 'preview' ? (
              <>
                {generatedCode ? (
                  isMultiFile && projectFiles.length > 0 ? (
                    <div className={`h-full flex items-center justify-center bg-white ${
                      deviceView === 'mobile' ? 'p-4' : deviceView === 'tablet' ? 'p-8' : 'p-0'
                    }`}>
                      {buildStatus === 'queued' || buildStatus === 'building' ? (
                        <div className="text-center">
                          <div className="animate-spin rounded-full h-12 w-12 border-4 border-wapify-accent border-t-transparent mx-auto mb-4"></div>
                          <p className="text-wapify-text-secondary">Compilation...</p>
                        </div>
                      ) : buildStatus === 'completed' && buildUrl ? (
                        <div className={`h-full ${
                          deviceView === 'mobile' ? 'max-w-[375px]' : deviceView === 'tablet' ? 'max-w-[768px]' : 'w-full'
                        } bg-white shadow-2xl rounded-xl overflow-hidden border-2 border-wapify-border`}>
                          <iframe
                            src={buildUrl}
                            className="w-full h-full border-none"
                            sandbox="allow-scripts allow-forms allow-modals allow-popups allow-same-origin allow-downloads"
                            title="App Preview"
                          />
                        </div>
                      ) : buildStatus === 'failed' ? (
                        <div className="text-center p-8">
                          <div className="text-6xl mb-4">❌</div>
                          <h3 className="text-2xl font-bold text-red-600 mb-2">Échec du build</h3>
                          <p className="text-wapify-text-secondary mb-4">{error || 'Une erreur est survenue'}</p>
                          <button
                            onClick={() => {
                              if (projectId) {
                                rebuildProject(projectId)
                              } else if (projectFiles.length > 0) {
                                setBuildStatus('idle')
                                triggerBuild(projectFiles, `temp-${Date.now()}`)
                              }
                            }}
                            className="px-6 py-3 bg-wapify-accent text-white rounded-xl font-semibold hover:bg-wapify-accent-dark transition shadow-md"
                          >
                            🔄 Réessayer
                          </button>
                        </div>
                      ) : (
                        <div className="animate-spin rounded-full h-12 w-12 border-4 border-wapify-accent border-t-transparent"></div>
                      )}
                    </div>
                  ) : (
                    <iframe
                      ref={iframeRef}
                      srcDoc={generatedCode}
                      className="w-full h-full border-none"
                      sandbox="allow-scripts"
                      title="App Preview"
                    />
                  )
                ) : (
                  <div className="flex items-center justify-center h-full text-center p-8">
                    <div>
                      <div className="text-6xl mb-4 opacity-50">🚀</div>
                      <h3 className="text-2xl font-bold text-wapify-text mb-2">Prêt à créer ?</h3>
                      <p className="text-wapify-text-secondary max-w-md">
                        Décrivez votre app dans le chat et l'IA choisira automatiquement le meilleur framework et style
                      </p>
                    </div>
                  </div>
                )}
              </>
            ) : (
              <div className="w-full h-full flex">
                <div className="w-64 bg-wapify-panel border-r-2 border-wapify-border overflow-auto">
                  <div className="p-2 border-b-2 border-wapify-border">
                    <div className="text-xs font-semibold text-wapify-text-secondary uppercase">Explorer</div>
                  </div>
                  <div className="p-2">
                    {projectFiles.length > 0 ? (
                      <div>{renderFileTree(buildFileTree(projectFiles))}</div>
                    ) : (
                      <div className="text-center py-8 text-wapify-text-secondary text-sm">
                        Aucun fichier
                      </div>
                    )}
                  </div>
                </div>

                <div className="flex-1 flex flex-col">
                  {selectedFile ? (
                    <>
                      <div className="px-4 py-2 text-sm border-b-2 border-wapify-border flex items-center justify-between bg-wapify-panel">
                        <span className="text-wapify-text">{selectedFile}</span>
                        <button
                          onClick={async () => {
                            if (!projectId) {
                              alert('Veuillez d\'abord sauvegarder le projet')
                              return
                            }

                            try {
                              const updatedFiles = projectFiles.map(f =>
                                f.path === selectedFile ? { ...f, content: fileContent } : f
                              )
                              setProjectFiles(updatedFiles)

                              const userId = (session?.user as any)?.id || session?.user?.email
                              const response = await fetch(`/api/projects/${projectId}/files`, {
                                method: 'PUT',
                                headers: { 'Content-Type': 'application/json' },
                                body: JSON.stringify({ userId, files: updatedFiles })
                              })

                              if (response.ok) {
                                alert('✅ Fichier sauvegardé !')
                                setLastSaved(new Date())

                                if (window.confirm('Reconstruire l\'app pour voir les changements ?')) {
                                  await rebuildProject(projectId)
                                }
                              } else {
                                throw new Error('Échec de la sauvegarde')
                              }
                            } catch (error) {
                              alert('❌ Erreur: ' + (error as Error).message)
                            }
                          }}
                          className="px-3 py-1 bg-wapify-accent text-white rounded-lg text-xs font-semibold hover:bg-wapify-accent-dark transition shadow-md"
                        >
                          💾 Sauvegarder
                        </button>
                      </div>
                      <Editor
                        height="100%"
                        language={
                          selectedFile.endsWith('.tsx') || selectedFile.endsWith('.ts') ? 'typescript' :
                          selectedFile.endsWith('.jsx') || selectedFile.endsWith('.js') ? 'javascript' :
                          selectedFile.endsWith('.css') ? 'css' :
                          selectedFile.endsWith('.json') ? 'json' :
                          selectedFile.endsWith('.html') ? 'html' : 'plaintext'
                        }
                        theme="vs-dark"
                        value={fileContent}
                        onChange={(value) => setFileContent(value || '')}
                        options={{
                          minimap: { enabled: true },
                          fontSize: 14,
                          lineHeight: 22,
                          scrollBeyondLastLine: false,
                          automaticLayout: true,
                        }}
                      />
                    </>
                  ) : (
                    <div className="flex items-center justify-center h-full text-wapify-text-secondary">
                      <div className="text-center">
                        <div className="text-6xl mb-4">💻</div>
                        <p>Sélectionnez un fichier pour l'éditer</p>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
