'use client'

import { useState, useEffect, useRef, useCallback } from 'react'
import { useSession, signOut } from 'next-auth/react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import JSZip from 'jszip'
import Editor from '@monaco-editor/react'
import { GenerationPlan, GenerationStep, ModificationDetail} from '../../lib/anthropic'
import { generateProject } from '../../lib/generate-client'

interface Message {
  role: 'user' | 'assistant'
  content: string
  id: string
  timestamp: Date
}

interface ProjectFile {
  path: string
  content: string
  type?: string
}

export default function EditorPage() {
  const { data: session, status } = useSession()
  const router = useRouter()
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [generatedCode, setGeneratedCode] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [generationPlan, setGenerationPlan] = useState<GenerationPlan | null>(null)
  const [, setSteps] = useState<GenerationStep[]>([])
  const [, setSubSteps] = useState<Array<{step: string, status: string, description: string, progress: number}>>([])
  const [, setModifications] = useState<ModificationDetail[]>([])
  const [error, setError] = useState('')
  const [, setHasAutoGenerated] = useState(false)
  const [, setCurrentGenerationMessageId] = useState<string | null>(null)
  const [, setShowStuckMessage] = useState(false)
  const [projectId, setProjectId] = useState<string | null>(null)
  const [projectName, setProjectName] = useState<string>('')
  const [isSaving, setIsSaving] = useState(false)
  const [lastSaved, setLastSaved] = useState<Date | null>(null)
  const [isMultiFile, setIsMultiFile] = useState(false)
  const [projectFiles, setProjectFiles] = useState<Array<{path: string, content: string, type?: string}>>([])
  const [hasDatabase, setHasDatabase] = useState(false)
  const [databaseSchema, setDatabaseSchema] = useState<string | null>(null)
  const [dbBranchId, setDbBranchId] = useState<string | null>(null)
  const [dbConnectionString, setDbConnectionString] = useState<string | null>(null)
  const [githubRepo, setGithubRepo] = useState<string | null>(null)
  const [githubRepoFullName, setGithubRepoFullName] = useState<string | null>(null)
  const [githubCloneUrl, setGithubCloneUrl] = useState<string | null>(null)
  const [activeView, setActiveView] = useState<'preview' | 'code' | 'dashboard'>('preview')
  const [selectedFile, setSelectedFile] = useState<string | null>(null)
  const [fileContent, setFileContent] = useState<string>('')
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set(['src', 'public']))
  const [deviceView, setDeviceView] = useState<'desktop' | 'tablet' | 'mobile'>('desktop')

  // Build server states
  const [buildJobId, setBuildJobId] = useState<string | null>(null)
  const [buildUrl, setBuildUrl] = useState<string | null>(null)
  const [buildStatus, setBuildStatus] = useState<'idle' | 'queued' | 'building' | 'completed' | 'failed'>('idle')

  // New UI states for professional navigation
  const [isUserMenuOpen, setIsUserMenuOpen] = useState(false)
  const [isChatCollapsed, setIsChatCollapsed] = useState(false)
  const [chatWidth, setChatWidth] = useState(420) // Default width in pixels
  const [isResizing, setIsResizing] = useState(false)
  const [showResourceMonitor, setShowResourceMonitor] = useState(false)

  const messagesEndRef = useRef<HTMLDivElement>(null)
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const [collapsedSections, setCollapsedSections] = useState<Set<string>>(new Set())
  const stepsEndRef = useRef<HTMLDivElement>(null)
  const hasInitialized = useRef(false)
  const lastProgressUpdateTime = useRef<number>(Date.now())
  const stuckMessageTimer = useRef<NodeJS.Timeout | null>(null)
  const hasSavedGeneration = useRef(false)
  const resizeStartX = useRef<number>(0)
  const resizeStartWidth = useRef<number>(0)

  // Mouse drag handlers for resizable chat panel
  const handleMouseDown = (e: React.MouseEvent) => {
    setIsResizing(true)
    resizeStartX.current = e.clientX
    resizeStartWidth.current = chatWidth
  }

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (!isResizing) return

      const delta = e.clientX - resizeStartX.current
      const newWidth = resizeStartWidth.current + delta

      // Min width: 450px (fixed), Max width: 700px
      const constrainedWidth = Math.max(450, Math.min(700, newWidth))
      setChatWidth(constrainedWidth)
    }

    const handleMouseUp = () => {
      setIsResizing(false)
    }

    if (isResizing) {
      document.addEventListener('mousemove', handleMouseMove)
      document.addEventListener('mouseup', handleMouseUp)
    }

    return () => {
      document.removeEventListener('mousemove', handleMouseMove)
      document.removeEventListener('mouseup', handleMouseUp)
    }
  }, [isResizing])

  // Redirection si non authentifié
  useEffect(() => {
    if (status === 'unauthenticated') {
      const urlParams = new URLSearchParams(window.location.search)
      const promptFromUrl = urlParams.get('prompt')

      if (promptFromUrl) {
        const callbackUrl = `/editor?prompt=${encodeURIComponent(promptFromUrl)}`
        router.push(`/auth/signin?callbackUrl=${encodeURIComponent(callbackUrl)}`)
      } else {
        router.push('/auth/signin?callbackUrl=/editor')
      }
    }
  }, [status, router])

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  // Fonction pour sauvegarder le projet
  const saveProject = useCallback(async (code: string, prompt: string) => {
    if ((!code && !isMultiFile) || !prompt || !session?.user?.email) return

    try {
      setIsSaving(true)
      const userId = (session.user as any)?.id || session.user.email
      const isTemporaryId = projectId?.startsWith('proj-')

      if (!projectId || isTemporaryId) {
        const name = projectName || `Projet ${new Date().toLocaleDateString()}`
        const requestBody: any = { userId, name, prompt }

        if (isMultiFile) {
          requestBody.files = projectFiles
          requestBody.framework = 'react'
          requestBody.hasDatabase = hasDatabase
          requestBody.databaseSchema = databaseSchema
        } else {
          requestBody.code = code
        }

        const response = await fetch('/api/projects', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(requestBody),
        })

        if (response.ok) {
          const { project } = await response.json()
          setProjectId(project.id)
          setProjectName(project.name)
          setLastSaved(new Date())
          window.history.pushState({}, '', `/editor?projectId=${project.id}`)
        }
      } else {
        const requestBody: any = { projectId, status: 'ready' }

        if (isMultiFile) {
          requestBody.files = projectFiles
          requestBody.hasDatabase = hasDatabase
          requestBody.databaseSchema = databaseSchema
          if (dbBranchId) requestBody.dbBranchId = dbBranchId
          if (dbConnectionString) requestBody.dbConnectionString = dbConnectionString
          if (githubRepo) requestBody.githubRepo = githubRepo
          if (githubRepoFullName) requestBody.githubRepoFullName = githubRepoFullName
          if (githubCloneUrl) requestBody.githubCloneUrl = githubCloneUrl
        } else {
          requestBody.code = code
        }

        const response = await fetch('/api/projects', {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(requestBody),
        })

        if (response.ok) {
          setLastSaved(new Date())
        }
      }
    } catch (error) {
      console.error('Erreur lors de la sauvegarde:', error)
    } finally {
      setIsSaving(false)
    }
  }, [projectId, projectName, session, isMultiFile, projectFiles, hasDatabase, databaseSchema, dbBranchId, dbConnectionString])

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  useEffect(() => {
    if (!isMultiFile && generatedCode && messages.length > 0) {
      const lastUserMessage = messages.filter(m => m.role === 'user').slice(-1)[0]
      if (lastUserMessage) {
        saveProject(generatedCode, lastUserMessage.content)
      }
    }
  }, [generatedCode, messages, saveProject, isMultiFile])

  useEffect(() => {
    if (!isGenerating && isMultiFile && projectFiles.length > 0 && messages.length > 0 && !hasSavedGeneration.current) {
      const lastUserMessage = messages.filter(m => m.role === 'user').slice(-1)[0]
      if (lastUserMessage) {
        saveProject('', lastUserMessage.content)
        hasSavedGeneration.current = true
      }
    }
  }, [isGenerating, projectFiles, messages, saveProject, isMultiFile, projectId])

  const downloadProject = useCallback(async () => {
    if (projectFiles.length === 0) {
      alert('No files to download')
      return
    }

    try {
      const zip = new JSZip()
      projectFiles.forEach(file => {
        const cleanPath = file.path.startsWith('/') ? file.path.slice(1) : file.path
        zip.file(cleanPath, file.content)
      })

      const readme = `# ${projectName || 'React Project'}\n\nGenerated by Wapify\n\n## Installation\n\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Development\n\n\`\`\`bash\nnpm run dev\n\`\`\``
      zip.file('README.md', readme)

      const blob = await zip.generateAsync({ type: 'blob' })
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `${projectName || 'projet'}-${Date.now()}.zip`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
    } catch (error) {
      console.error('Error creating ZIP:', error)
      alert('Error creating ZIP file')
    }
  }, [projectFiles, projectName])

  useEffect(() => {
    if (stepsEndRef.current && isGenerating) {
      const timer = setTimeout(() => {
        stepsEndRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' })
      }, 100)
      return () => clearTimeout(timer)
    }
  }, [isGenerating])

  useEffect(() => {
    if (hasInitialized.current) return
    hasInitialized.current = true

    if (typeof window !== 'undefined') {
      const urlParams = new URLSearchParams(window.location.search)
      const projectIdFromUrl = urlParams.get('projectId')
      const promptFromUrl = urlParams.get('prompt')
      const styleFromUrl = urlParams.get('style')

      if (projectIdFromUrl) {
        loadProject(projectIdFromUrl)
      } else if (promptFromUrl && promptFromUrl.trim()) {
        setHasAutoGenerated(true)

        let finalPrompt = promptFromUrl
        if (styleFromUrl) {
          const styleInstructions: Record<string, string> = {
            modern: "Use a modern minimalist design with generous whitespace, clean sans-serif typography, subtle animations, and a neutral color palette with accent colors.",
            gradient: "Use bold gradient backgrounds with vibrant colors, smooth color transitions, animated elements with hover effects, and modern glassmorphism with blur effects.",
            dark: "Use a dark mode design with dark backgrounds, neon accent colors for CTAs, high contrast for readability, and strategic highlights.",
            brutalist: "Use a brutalist design with heavy black borders, bold geometric shapes, strong typography hierarchy, and high contrast black and white colors.",
            glassmorphism: "Use glassmorphism design with frosted glass blur effects on cards, soft drop shadows, translucent backgrounds with vibrant colors, and depth layers."
          }
          const instructions = styleInstructions[styleFromUrl]
          if (instructions) {
            finalPrompt = `${promptFromUrl} ${instructions}`
          }
        }

        handleGenerateWithPrompt(finalPrompt)
        window.history.replaceState({}, '', '/editor')
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const loadProject = async (id: string) => {
    try {
      const response = await fetch(`/api/projects/${id}`)
      if (!response.ok) {
        throw new Error('Projet introuvable')
      }

      const data = await response.json()
      const project = data.project

      setProjectId(project.id)
      setProjectName(project.name)

      if (project.framework === 'react') {
        setIsMultiFile(true)
        setHasDatabase(project.has_database || false)

        if (data.files && Array.isArray(data.files) && data.files.length > 0) {
          setProjectFiles(data.files)
          setGeneratedCode('multi-file-project')
          if (data.files.length > 0) {
            setSelectedFile(data.files[0].path)
          }
        } else {
          setError('Ce projet React n\'a aucun fichier sauvegardé')
          setProjectFiles([])
          setGeneratedCode('')
        }
      } else if (project.code) {
        setIsMultiFile(false)
        setGeneratedCode(project.code)
      }

      const initialMessage: Message = {
        role: 'user',
        content: project.prompt,
        id: `msg-${Date.now()}`,
        timestamp: new Date(project.created_at)
      }
      setMessages([initialMessage])
    } catch (err) {
      setError('Impossible de charger ce projet')
      console.error('Error loading project:', err)
    }
  }

  const handleGenerateWithPrompt = useCallback(async (promptText: string) => {
    if (!promptText.trim() || isGenerating) return

    const messageId = `msg-${Date.now()}`
    const userMessage: Message = {
      role: 'user',
      content: promptText,
      id: messageId,
      timestamp: new Date()
    }
    setMessages(prev => [...prev, userMessage])
    setCurrentGenerationMessageId(messageId)
    setInput('')
    setIsGenerating(true)
    setError('')
    setSteps([])
    setSubSteps([])
    setGenerationPlan(null)
    setModifications([])
    hasSavedGeneration.current = false

    try {
      const currentProjectId = projectId || `proj-${Date.now()}-${Math.random().toString(36).substring(7)}`
      if (!projectId) {
        setProjectId(currentProjectId)
      }

      const result = await generateProject({
        prompt: promptText,
        conversationHistory: messages,
        projectId: currentProjectId,
        userId: (session?.user as any)?.id || session?.user?.email,
        onProgress: (progress) => {
          console.log(`Generation progress: ${progress}%`)
        },
        onEvent: (event) => {
          if (event.type === 'plan') {
            setGenerationPlan(event.data)
          } else if (event.type === 'modifications') {
            setModifications(event.data)
          } else if (event.type === 'chat_message') {
            const chatMessage: Message = {
              role: 'assistant',
              content: event.data,
              id: `msg-gen-${Date.now()}-${Math.random()}`,
              timestamp: new Date()
            }
            setMessages(prev => [...prev, chatMessage])
          } else if (event.type === 'step') {
            setSteps(prev => {
              const existingIndex = prev.findIndex(s => s.step === event.data.step)
              if (existingIndex >= 0) {
                const newSteps = [...prev]
                newSteps[existingIndex] = event.data
                return newSteps
              }
              return [...prev, event.data]
            })
          } else if (event.type === 'substep') {
            lastProgressUpdateTime.current = Date.now()
            setShowStuckMessage(false)
            if (stuckMessageTimer.current) {
              clearTimeout(stuckMessageTimer.current)
            }
            stuckMessageTimer.current = setTimeout(() => {
              setShowStuckMessage(true)
            }, 5000)
            setSubSteps(prev => {
              const existingIndex = prev.findIndex(s => s.step === event.data.step)
              if (existingIndex >= 0) {
                const newSubSteps = [...prev]
                newSubSteps[existingIndex] = event.data
                return newSubSteps
              }
              return [...prev, event.data]
            })
          }
        }
      })

      if (result.isMultiFile) {
        setIsMultiFile(true)
        setProjectFiles(result.files)
        setHasDatabase(result.hasDatabase || false)
        setDatabaseSchema(result.databaseSchema || null)
        if (result.dbBranchId) {
          setDbBranchId(result.dbBranchId)
        }
        if (result.dbConnectionString) {
          setDbConnectionString(result.dbConnectionString)
        }
        if (result.githubRepo) {
          setGithubRepo(result.githubRepo)
          setGithubRepoFullName(result.githubRepoFullName || null)
          setGithubCloneUrl(result.githubCloneUrl || null)
        }

        const defaultFile = result.files.find((f: any) =>
          f.path === 'src/App.jsx' || f.path === 'src/App.tsx' || f.path === 'src/main.jsx'
        ) || result.files[0]

        if (defaultFile) {
          setSelectedFile(defaultFile.path)
          setGeneratedCode(defaultFile.content)
        }
      } else {
        setIsMultiFile(false)
        setGeneratedCode(result.files[0]?.content || '')
      }

      const assistantMessage: Message = {
        role: 'assistant',
        content: 'Application generated successfully! You can see it in the preview and request modifications.',
        id: `msg-${Date.now()}`,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, assistantMessage])

    } catch (err) {
      console.error('Generation error:', err)
      setError(err instanceof Error ? err.message : 'Generation error')

      const errorMessage: Message = {
        role: 'assistant',
        content: `❌ Error: ${err instanceof Error ? err.message : 'Generation error'}`,
        id: `msg-${Date.now()}`,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, errorMessage])
    } finally {
      setIsGenerating(false)
      setShowStuckMessage(false)
      if (stuckMessageTimer.current) {
        clearTimeout(stuckMessageTimer.current)
        stuckMessageTimer.current = null
      }
    }
  }, [isGenerating, messages, generationPlan])

  const handleGenerate = async () => {
    if (!input.trim() || isGenerating) return
    await handleGenerateWithPrompt(input)
  }

  const triggerBuild = async (files: Array<{path: string, content: string}>, projId: string) => {
    try {
      setBuildStatus('queued')

      const buildMessage: Message = {
        role: 'assistant',
        content: '🔨 Building with Vite...',
        id: `msg-build-${Date.now()}`,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, buildMessage])

      const response = await fetch('/api/build', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          projectId: projId || `temp-${Date.now()}`,
          files,
          projectName: projectName || 'Wapify App'
        })
      })

      if (!response.ok) {
        throw new Error('Failed to trigger build')
      }

      const data = await response.json()
      setBuildJobId(data.jobId)
      setBuildStatus('building')
    } catch (error) {
      console.error('Error triggering build:', error)
      setBuildStatus('failed')
      setError('Failed to start build')

      const errorMessage: Message = {
        role: 'assistant',
        content: '❌ Build error',
        id: `msg-build-error-${Date.now()}`,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, errorMessage])
    }
  }

  const rebuildProject = async (projId: string) => {
    try {
      setBuildStatus('queued')
      setError('')

      const response = await fetch(`/api/projects/${projId}/rebuild`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' }
      })

      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || 'Failed to rebuild project')
      }

      const data = await response.json()
      setBuildJobId(data.jobId)
      setBuildStatus('building')
    } catch (error) {
      console.error('Error rebuilding project:', error)
      setBuildStatus('failed')
      setError(error instanceof Error ? error.message : 'Rebuild failed')
    }
  }

  const convertToProxyUrl = (blobUrl: string): string => {
    try {
      const url = new URL(blobUrl)
      const pathParts = url.pathname.split('/').filter(Boolean)
      if (pathParts.length >= 3) {
        return `/api/preview/${pathParts.join('/')}`
      }
    } catch (e) {
      console.error('Failed to convert URL:', e)
    }
    return blobUrl
  }

  const handleBuildComplete = (url: string) => {
    const proxyUrl = convertToProxyUrl(url)
    setBuildUrl(proxyUrl)
    setBuildStatus('completed')

    const successMessage: Message = {
      role: 'assistant',
      content: '✅ Build successful! Your application is ready.',
      id: `msg-build-success-${Date.now()}`,
      timestamp: new Date()
    }
    setMessages(prev => [...prev, successMessage])
  }

  const handleBuildError = (error: string) => {
    console.error('Build failed:', error)
    setBuildStatus('failed')
    setError(`Build error: ${error}`)

    const errorMessage: Message = {
      role: 'assistant',
      content: `❌ Build error: ${error}`,
      id: `msg-build-error-${Date.now()}`,
      timestamp: new Date()
    }
    setMessages(prev => [...prev, errorMessage])
  }

  useEffect(() => {
    if (isMultiFile && projectFiles.length > 0 && buildStatus === 'idle') {
      const currentProjectId = projectId || `temp-${Date.now()}`
      triggerBuild(projectFiles, currentProjectId)
    }
  }, [projectFiles, isMultiFile, buildStatus, projectId])

  useEffect(() => {
    if (buildStatus === 'building' && buildJobId) {
      const pollInterval = setInterval(async () => {
        try {
          const response = await fetch(`/api/build?jobId=${buildJobId}`)
          if (response.ok) {
            const data = await response.json()

            if (data.status === 'completed' && data.url) {
              handleBuildComplete(data.url)
              clearInterval(pollInterval)
            } else if (data.status === 'failed') {
              handleBuildError(data.error || 'Build failed')
              clearInterval(pollInterval)
            }
          }
        } catch (error) {
          console.error('Error polling build status:', error)
        }
      }, 2000)

      return () => clearInterval(pollInterval)
    }
  }, [buildStatus, buildJobId, handleBuildComplete, handleBuildError])

  const handleModification = async () => {
    if (!input.trim() || isGenerating || !generatedCode) return

    const messageId = `msg-${Date.now()}`
    const userMessage: Message = {
      role: 'user',
      content: input,
      id: messageId,
      timestamp: new Date()
    }
    setMessages(prev => [...prev, userMessage])
    setCurrentGenerationMessageId(messageId)
    setInput('')
    setIsGenerating(true)
    setError('')
    setSteps([])
    setModifications([])

    try {
      const requestBody: any = {
        modification: userMessage.content,
        conversationHistory: messages,
        isMultiFile
      }

      if (isMultiFile) {
        requestBody.projectFiles = projectFiles
      } else {
        requestBody.currentCode = generatedCode
      }

      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody)
      })

      if (!response.ok) {
        throw new Error('Modification error')
      }

      const reader = response.body?.getReader()
      const decoder = new TextDecoder()

      if (!reader) {
        throw new Error('No stream available')
      }

      let buffer = ''

      while (true) {
        const { done, value } = await reader.read()

        if (done) break

        buffer += decoder.decode(value, { stream: true })
        const lines = buffer.split('\n\n')
        buffer = lines.pop() || ''

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            const data = line.slice(6)
            try {
              const event = JSON.parse(data)

              if (event.type === 'step') {
                setSteps(prev => {
                  const existingIndex = prev.findIndex(s => s.step === event.data.step)
                  if (existingIndex >= 0) {
                    const newSteps = [...prev]
                    newSteps[existingIndex] = event.data
                    return newSteps
                  }
                  return [...prev, event.data]
                })
              } else if (event.type === 'complete') {
                if (event.data.isMultiFile && event.data.files) {
                  setProjectFiles(event.data.files)

                  const mainFile = event.data.files.find((f: any) =>
                    f.path === 'src/App.jsx' || f.path === 'src/main.jsx'
                  ) || event.data.files[0]

                  if (mainFile) {
                    setGeneratedCode(mainFile.content)
                  }
                } else if (event.data.code) {
                  setGeneratedCode(event.data.code)
                }

                const assistantMessage: Message = {
                  role: 'assistant',
                  content: '✨ Modification applied successfully!',
                  id: `msg-${Date.now()}`,
                  timestamp: new Date()
                }
                setMessages(prev => [...prev, assistantMessage])
              } else if (event.type === 'error') {
                throw new Error(event.data.message)
              }
            } catch (e) {
              console.error('Erreur lors du parsing de l\'événement:', e)
            }
          }
        }
      }
    } catch (err) {
      console.error('Modification error:', err)
      setError(err instanceof Error ? err.message : 'Modification error')

      const errorMessage: Message = {
        role: 'assistant',
        content: `❌ Error: ${err instanceof Error ? err.message : 'Modification error'}`,
        id: `msg-${Date.now()}`,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, errorMessage])
    } finally {
      setIsGenerating(false)
    }
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    if (!generatedCode) {
      handleGenerate()
    } else {
      handleModification()
    }
  }

  const downloadCode = () => {
    const blob = new Blob([generatedCode], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `wapify-app-${Date.now()}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const resetProject = () => {
    setMessages([])
    setGeneratedCode('')
    setGenerationPlan(null)
    setSteps([])
    setError('')
  }

  useEffect(() => {
    console.log(`projectFiles state changed:`, {
      length: projectFiles.length,
      isMultiFile,
      generatedCode: generatedCode ? 'exists' : 'null',
      files: projectFiles.map(f => f.path)
    })
  }, [projectFiles, isMultiFile, generatedCode])

  if (status === 'loading') {
    return (
      <div className="min-h-screen bg-wapify-bg flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-wapify-accent border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-wapify-text-secondary">Loading...</p>
        </div>
      </div>
    )
  }

  // File tree helpers
  interface FileNode {
    name: string
    path: string
    type: 'file' | 'folder'
    children?: FileNode[]
    content?: string
  }

  const buildFileTree = (files: Array<{path: string, content: string}>): FileNode[] => {
    const root: FileNode[] = []

    files.forEach(file => {
      const parts = file.path.split('/')
      let currentLevel = root

      parts.forEach((part, index) => {
        const isFile = index === parts.length - 1
        const existingNode = currentLevel.find(node => node.name === part)

        if (existingNode) {
          if (!isFile && existingNode.children) {
            currentLevel = existingNode.children
          }
        } else {
          const newNode: FileNode = {
            name: part,
            path: parts.slice(0, index + 1).join('/'),
            type: isFile ? 'file' : 'folder',
            children: isFile ? undefined : [],
            content: isFile ? file.content : undefined
          }
          currentLevel.push(newNode)
          if (!isFile && newNode.children) {
            currentLevel = newNode.children
          }
        }
      })
    })

    return root
  }

  const toggleFolder = (folderPath: string) => {
    setExpandedFolders(prev => {
      const newSet = new Set(prev)
      if (newSet.has(folderPath)) {
        newSet.delete(folderPath)
      } else {
        newSet.add(folderPath)
      }
      return newSet
    })
  }

  const getFileIcon = (fileName: string) => {
    if (fileName.endsWith('.tsx') || fileName.endsWith('.ts')) return '📘'
    if (fileName.endsWith('.jsx') || fileName.endsWith('.js')) return '📜'
    if (fileName.endsWith('.css')) return '🎨'
    if (fileName.endsWith('.json')) return '📋'
    if (fileName.endsWith('.html')) return '🌐'
    return '📄'
  }

  const renderFileTree = (nodes: FileNode[], depth: number = 0): React.ReactElement[] => {
    return nodes.map((node) => {
      if (node.type === 'folder') {
        const isExpanded = expandedFolders.has(node.path)
        return (
          <div key={node.path}>
            <button
              onClick={() => toggleFolder(node.path)}
              className="w-full text-left px-2 py-1 text-sm transition flex items-center hover:bg-wapify-accent/10"
              style={{ paddingLeft: `${depth * 12 + 8}px` }}
            >
              <span className="mr-1 text-xs text-wapify-text-secondary">
                {isExpanded ? '▼' : '▶'}
              </span>
              <span className="mr-2">
                {isExpanded ? '📂' : '📁'}
              </span>
              <span className="text-wapify-text">{node.name}</span>
            </button>
            {isExpanded && node.children && (
              <div>{renderFileTree(node.children, depth + 1)}</div>
            )}
          </div>
        )
      } else {
        const isSelected = selectedFile === node.path
        return (
          <button
            key={node.path}
            onClick={() => {
              setSelectedFile(node.path)
              setFileContent(node.content || '')
            }}
            className={`w-full text-left px-2 py-1 text-sm transition flex items-center ${
              isSelected ? 'bg-wapify-accent/20 text-wapify-text' : 'text-wapify-text-secondary hover:bg-wapify-accent/10 hover:text-wapify-text'
            }`}
            style={{ paddingLeft: `${depth * 12 + 24}px` }}
          >
            <span className="mr-2">{getFileIcon(node.name)}</span>
            {node.name}
          </button>
        )
      }
    })
  }

  if (!session) {
    return null
  }

  return (
    <div className="h-screen flex flex-col bg-wapify-bg">
      <div className="grain-texture"></div>

      {/* Top Navigation */}
      <nav className="h-14 bg-wapify-panel border-b-2 border-wapify-border flex items-center justify-between px-4 flex-shrink-0 relative z-50">
        <div className="flex items-center gap-4">
          {/* Wapify Logo Dropdown */}
          <div className="relative">
            <button
              onClick={() => setIsUserMenuOpen(!isUserMenuOpen)}
              className="flex items-center gap-2 hover:opacity-80 transition group"
            >
              <div className="w-8 h-8 bg-gradient-to-br from-wapify-accent to-wapify-accent-dark rounded-lg flex items-center justify-center text-base shadow-md">
                ⚡
              </div>
              <svg className={`w-4 h-4 text-wapify-text-secondary transition-transform ${isUserMenuOpen ? 'rotate-180' : ''}`} fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd"/>
              </svg>
            </button>

            {/* Dropdown Menu */}
            {isUserMenuOpen && (
              <>
                <div className="fixed inset-0 z-10" onClick={() => setIsUserMenuOpen(false)}></div>
                <div className="absolute top-full left-0 mt-2 w-56 bg-wapify-panel border-2 border-wapify-border rounded-xl shadow-2xl overflow-hidden z-20">
                  <Link
                    href="/dashboard"
                    className="flex items-center gap-3 px-4 py-3 text-sm text-wapify-text hover:bg-wapify-bg transition border-b border-wapify-border"
                    onClick={() => setIsUserMenuOpen(false)}
                  >
                    <span>←</span>
                    <span>Back to Workspace</span>
                  </Link>

                  <div className="px-4 py-3 bg-wapify-bg border-b border-wapify-border">
                    <div className="text-xs text-wapify-text-secondary mb-1">Signed in as</div>
                    <div className="text-sm font-semibold text-wapify-text truncate">{session?.user?.email}</div>
                  </div>

                  <div className="px-4 py-3 bg-wapify-bg border-b border-wapify-border">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-xs text-wapify-text-secondary">Credits</span>
                      <span className="text-sm font-bold text-wapify-accent">∞</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-xs text-wapify-text-secondary">Plan</span>
                      <span className="text-xs font-semibold text-wapify-text bg-wapify-accent/10 px-2 py-0.5 rounded-full">Free Trial</span>
                    </div>
                  </div>

                  <Link href="/docs" className="flex items-center gap-3 px-4 py-2.5 text-sm text-wapify-text-secondary hover:bg-wapify-bg hover:text-wapify-text transition" onClick={() => setIsUserMenuOpen(false)}>
                    <span>📖</span>
                    <span>Documentation</span>
                  </Link>

                  <button className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-wapify-text-secondary hover:bg-wapify-bg hover:text-wapify-text transition text-left">
                    <span>⚙️</span>
                    <span>Settings</span>
                  </button>

                  <button className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-wapify-text-secondary hover:bg-wapify-bg hover:text-wapify-text transition text-left">
                    <span>💳</span>
                    <span>Billing</span>
                  </button>

                  <Link href="/support" className="flex items-center gap-3 px-4 py-2.5 text-sm text-wapify-text-secondary hover:bg-wapify-bg hover:text-wapify-text transition" onClick={() => setIsUserMenuOpen(false)}>
                    <span>💬</span>
                    <span>Help Center</span>
                  </Link>

                  <Link href="/pricing" className="flex items-center gap-3 px-4 py-2.5 text-sm text-wapify-accent hover:bg-wapify-bg transition font-semibold border-t border-wapify-border" onClick={() => setIsUserMenuOpen(false)}>
                    <span>⭐</span>
                    <span>Upgrade Plan</span>
                  </Link>

                  <button
                    onClick={() => {
                      setIsUserMenuOpen(false)
                      signOut({ callbackUrl: '/' })
                    }}
                    className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-red-600 hover:bg-red-50 transition text-left border-t border-wapify-border"
                  >
                    <span>🚪</span>
                    <span>Sign Out</span>
                  </button>
                </div>
              </>
            )}
          </div>

          {/* Project Name */}
          <div className="flex items-center gap-2 px-3 py-1.5 bg-wapify-bg rounded-lg">
            <span className="text-sm font-semibold text-wapify-text">{projectName || 'Untitled Project'}</span>
          </div>

          {/* Divider */}
          <div className="h-8 w-[1px] bg-wapify-border"></div>

          {/* Toggle Sidebar Button */}
          <button
            onClick={() => setIsChatCollapsed(!isChatCollapsed)}
            className="p-1.5 text-gray-500 hover:bg-gray-200 rounded-md transition-colors"
            title={isChatCollapsed ? 'Show Sidebar' : 'Hide Sidebar'}
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <rect width="18" height="18" x="3" y="3" rx="2"></rect>
              <path d="M9 3v18"></path>
              <path d={isChatCollapsed ? "m14 9 3 3-3 3" : "m16 15-3-3 3-3"}></path>
            </svg>
          </button>

          {/* Help Button */}
          <button
            onClick={() => window.open('mailto:support@wapify.com?subject=Help Request', '_blank')}
            className="w-7 h-7 rounded-full border-2 border-gray-300 bg-white hover:bg-gray-100 hover:border-gray-400 transition flex items-center justify-center text-sm font-bold text-gray-600"
            title="Contact Wapify Support"
          >
            ?
          </button>

          {/* Tabs Container */}
          <div className="inline-flex items-center justify-center bg-gray-100 p-1 text-gray-500 h-7 rounded-lg">
            <button
              onClick={() => setActiveView('preview')}
              className={`inline-flex items-center justify-center whitespace-nowrap px-3 py-1.5 text-sm font-medium transition-all h-6 rounded-md cursor-pointer ${
                activeView === 'preview'
                  ? 'bg-white text-gray-900 shadow-sm'
                  : 'text-gray-500 hover:text-gray-900'
              }`}
            >
              Preview
            </button>

            <button
              onClick={() => setActiveView('dashboard')}
              className={`inline-flex items-center justify-center whitespace-nowrap px-3 py-1.5 text-sm font-medium transition-all h-6 rounded-md cursor-pointer ${
                activeView === 'dashboard'
                  ? 'bg-white text-gray-900 shadow-sm'
                  : 'text-gray-500 hover:text-gray-900'
              }`}
            >
              Dashboard
            </button>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {lastSaved && (
            <div className="text-xs text-wapify-text-secondary flex items-center gap-2">
              {isSaving ? (
                <>
                  <div className="w-1.5 h-1.5 bg-wapify-accent rounded-full animate-pulse"></div>
                  <span>Saving...</span>
                </>
              ) : (
                <>
                  <div className="w-1.5 h-1.5 bg-green-500 rounded-full"></div>
                  <span>Saved {lastSaved.toLocaleTimeString()}</span>
                </>
              )}
            </div>
          )}

          {generatedCode && (
            <>
              <button
                onClick={isMultiFile ? downloadProject : downloadCode}
                className="px-3 py-1.5 bg-wapify-accent text-white rounded-lg font-semibold hover:bg-wapify-accent-dark transition shadow-sm text-xs"
              >
                📥 Download
              </button>
              <button
                onClick={resetProject}
                className="px-3 py-1.5 bg-wapify-border text-wapify-text rounded-lg font-semibold hover:bg-wapify-accent/10 transition text-xs"
              >
                New Project
              </button>
            </>
          )}
        </div>
      </nav>

      {/* Main Split-Pane Layout */}
      <div className="flex-1 flex overflow-hidden relative z-0">
        {/* Left Panel - Chat Interface */}
        {!isChatCollapsed && (
          <div
            className="bg-wapify-panel border-r-2 border-wapify-border flex flex-col relative z-0"
            style={{ width: `${chatWidth}px` }}
          >
            {/* Messages Area */}
            <div className="flex-1 overflow-y-auto p-4 space-y-3 pt-4">
              {messages.length === 0 && (
                <div className="text-center py-12">
                  <div className="text-5xl mb-4 opacity-50">✨</div>
                  <p className="text-sm text-wapify-text-secondary">
                    Start by describing your app
                  </p>
                </div>
              )}

              {messages.map((msg, idx) => (
                <div
                  key={idx}
                  className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} animate-fadeIn`}
                >
                  <div
                    className={`max-w-[85%] rounded-xl p-3 shadow-sm ${
                      msg.role === 'user'
                        ? 'bg-wapify-accent text-white'
                        : 'bg-white border-2 border-wapify-border text-wapify-text'
                    }`}
                  >
                    <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                    <p className="text-[10px] mt-1 opacity-60">{msg.timestamp.toLocaleTimeString()}</p>
                  </div>
                </div>
              ))}

              {isGenerating && (
                <div className="flex justify-start">
                  <div className="bg-white border-2 border-wapify-border rounded-xl p-3">
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 bg-wapify-accent rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                      <div className="w-2 h-2 bg-wapify-accent rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                      <div className="w-2 h-2 bg-wapify-accent rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
                    </div>
                  </div>
                </div>
              )}

              <div ref={messagesEndRef} />
            </div>

            {/* Input Area - Integrated */}
            <div className="border-t border-wapify-border flex-shrink-0 bg-wapify-bg p-4">
              <form onSubmit={handleSubmit} className="relative">
                <div className="bg-white border-2 border-wapify-border rounded-xl p-3 focus-within:border-wapify-accent transition">
                  {/* Textarea with Send Button */}
                  <div className="relative">
                    <textarea
                      value={input}
                      onChange={(e) => setInput(e.target.value)}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter' && !e.shiftKey) {
                          e.preventDefault()
                          handleSubmit(e)
                        }
                      }}
                      placeholder={!generatedCode ? "Describe your application..." : "Request a modification..."}
                      className="w-full px-3 py-3 pr-12 bg-transparent text-wapify-text placeholder-wapify-text-secondary focus:outline-none text-sm resize-none"
                      disabled={isGenerating}
                      rows={4}
                      style={{ minHeight: '100px' }}
                    />

                    {/* Send Button - Top Right */}
                    <button
                      type="submit"
                      disabled={isGenerating || !input.trim()}
                      className="absolute top-4 right-4 flex justify-center items-center w-[30px] h-[30px] p-1 text-white rounded-lg transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed bg-wapify-accent hover:bg-wapify-accent-dark"
                      aria-label="Send message"
                      title="Send message"
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="w-4 h-4">
                        <path d="m5 12 7-7 7 7"></path>
                        <path d="M12 19V5"></path>
                      </svg>
                    </button>
                  </div>

                  {/* Bottom Action Bar */}
                  <div className="flex items-center justify-between gap-2 mt-2 pt-2 border-t border-gray-100">
                    <div className="flex items-center gap-2">
                      {/* Attach Button */}
                      <button
                        type="button"
                        className="p-1.5 text-wapify-text-secondary hover:text-wapify-text hover:bg-gray-100 rounded-lg transition"
                        title="Attach files"
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                        </svg>
                      </button>

                      {/* Settings Button */}
                      <button
                        type="button"
                        className="flex items-center gap-1 px-2 py-1 text-wapify-text-secondary hover:text-wapify-text hover:bg-gray-100 rounded-lg transition text-xs"
                        title="Settings"
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>
                      </button>
                    </div>

                    {/* Visual Edit Button - Moved to right */}
                    <button
                      type="button"
                      className="flex items-center gap-1 px-2 py-1 text-wapify-text-secondary hover:text-wapify-text hover:bg-gray-100 rounded-lg transition text-xs font-medium"
                      title="Visual Edit"
                    >
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                      </svg>
                      <span>Visual Edit</span>
                    </button>
                  </div>
                </div>
              </form>
            </div>

            {/* Resize Handle */}
            <div
              className="absolute right-0 top-0 bottom-0 w-[1px] bg-gray-200 hover:bg-wapify-accent cursor-col-resize group"
              onMouseDown={handleMouseDown}
            >
              <div className="absolute inset-y-0 -right-1 -left-1"></div>
            </div>
          </div>
        )}

        {/* Right Panel - Preview & Code */}
        <div className="flex-1 flex flex-col bg-wapify-bg relative z-0">
          {/* Top Bar with Share/Publish buttons */}
          <div className="flex items-center justify-end px-4 py-3 border-b border-wapify-border flex-shrink-0">
            <div className="flex items-center gap-2">
              <button
                onClick={() => {
                  // TODO: Implémenter la fonctionnalité Share
                  alert('Share functionality coming soon!')
                }}
                disabled={!generatedCode}
                className="px-3 py-1.5 bg-gray-100 text-gray-700 rounded-lg font-semibold hover:bg-gray-200 transition text-sm border border-gray-300 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Share
              </button>
              <button
                onClick={() => {
                  // TODO: Implémenter la fonctionnalité Publish/Deploy
                  alert('Publish functionality coming soon!')
                }}
                disabled={!generatedCode}
                className="px-3 py-1.5 bg-wapify-accent text-white rounded-lg font-semibold hover:bg-wapify-accent-dark transition shadow-sm text-sm disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Publish
              </button>
            </div>
          </div>

          {/* Content Area */}
          <div className="flex-1 relative overflow-hidden">
            {activeView === 'preview' ? (
              <>
                {generatedCode ? (
                  isMultiFile && projectFiles.length > 0 ? (
                    <div className={`h-full flex flex-col items-center justify-center bg-white ${
                      deviceView === 'mobile' ? 'p-4' : deviceView === 'tablet' ? 'p-8' : 'p-0'
                    }`}>
                      <div className="flex-1 flex items-center justify-center w-full">
                        {buildStatus === 'queued' || buildStatus === 'building' ? (
                          <div className="text-center">
                            <div className="animate-spin rounded-full h-12 w-12 border-4 border-wapify-accent border-t-transparent mx-auto mb-4"></div>
                            <p className="text-wapify-text-secondary">Building...</p>
                          </div>
                        ) : buildStatus === 'completed' && buildUrl ? (
                          <div className={`h-full ${
                            deviceView === 'mobile' ? 'max-w-[375px]' : deviceView === 'tablet' ? 'max-w-[768px]' : 'w-full'
                          } bg-white shadow-2xl rounded-xl overflow-hidden border-2 border-wapify-border`}>
                            <iframe
                              src={buildUrl}
                              className="w-full h-full border-none"
                              sandbox="allow-scripts allow-forms allow-modals allow-popups allow-same-origin allow-downloads"
                              title="App Preview"
                            />
                          </div>
                        ) : buildStatus === 'failed' ? (
                          <div className="text-center p-8">
                            <div className="text-6xl mb-4">❌</div>
                            <h3 className="text-2xl font-bold text-red-600 mb-2">Build Failed</h3>
                            <p className="text-wapify-text-secondary mb-4">{error || 'An error occurred'}</p>
                            <button
                              onClick={() => {
                                if (projectId) {
                                  rebuildProject(projectId)
                                } else if (projectFiles.length > 0) {
                                  setBuildStatus('idle')
                                  triggerBuild(projectFiles, `temp-${Date.now()}`)
                                }
                              }}
                              className="flex items-center gap-2 px-6 py-3 bg-wapify-accent text-white rounded-xl font-semibold hover:bg-wapify-accent-dark transition shadow-md"
                            >
                              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                              </svg>
                              Retry
                            </button>
                          </div>
                        ) : (
                          <div className="animate-spin rounded-full h-12 w-12 border-4 border-wapify-accent border-t-transparent"></div>
                        )}
                      </div>

                      {/* Device View Selector - Bottom Center */}
                      <div className="flex items-center justify-center pb-4 pt-2">
                        <div className="flex items-center gap-1 bg-wapify-panel border-2 border-wapify-border rounded-lg p-1 shadow-lg">
                          <button
                            onClick={() => setDeviceView('mobile')}
                            className={`p-2 rounded transition ${
                              deviceView === 'mobile' ? 'bg-wapify-accent text-white' : 'text-wapify-text-secondary hover:text-wapify-text hover:bg-wapify-bg'
                            }`}
                            title="Mobile"
                          >
                            <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                              <path d="M7 3a2 2 0 00-2 2v10a2 2 0 002 2h6a2 2 0 002-2V5a2 2 0 00-2-2H7zm3 12a1 1 0 100-2 1 1 0 000 2z" />
                            </svg>
                          </button>
                          <button
                            onClick={() => setDeviceView('desktop')}
                            className={`p-2 rounded transition ${
                              deviceView === 'desktop' ? 'bg-wapify-accent text-white' : 'text-wapify-text-secondary hover:text-wapify-text hover:bg-wapify-bg'
                            }`}
                            title="Desktop"
                          >
                            <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                              <path d="M3 4a1 1 0 011-1h12a1 1 0 011 1v8a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 14h14v1a1 1 0 01-1 1H4a1 1 0 01-1-1v-1z" />
                            </svg>
                          </button>
                        </div>
                      </div>
                    </div>
                  ) : (
                    <iframe
                      ref={iframeRef}
                      srcDoc={generatedCode}
                      className="w-full h-full border-none"
                      sandbox="allow-scripts"
                      title="App Preview"
                    />
                  )
                ) : (
                  <div className="flex items-center justify-center h-full text-center p-8">
                    <div>
                      <svg className="w-24 h-24 mx-auto mb-4 text-wapify-accent opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
                      </svg>
                      <h3 className="text-2xl font-bold text-wapify-text mb-2">Ready to Build?</h3>
                      <p className="text-wapify-text-secondary max-w-md">
                        Describe your app in the chat and AI will automatically choose the best framework and style
                      </p>
                    </div>
                  </div>
                )}
              </>
            ) : activeView === 'code' ? (
              <div className="w-full h-full flex">
                <div className="w-64 bg-wapify-panel border-r-2 border-wapify-border overflow-auto">
                  <div className="p-2 border-b-2 border-wapify-border">
                    <div className="text-xs font-semibold text-wapify-text-secondary uppercase">Explorer</div>
                  </div>
                  <div className="p-2">
                    {projectFiles.length > 0 ? (
                      <div>{renderFileTree(buildFileTree(projectFiles))}</div>
                    ) : (
                      <div className="text-center py-8 text-wapify-text-secondary text-sm">
                        No files
                      </div>
                    )}
                  </div>
                </div>

                <div className="flex-1 flex flex-col">
                  {selectedFile ? (
                    <>
                      <div className="px-4 py-2 text-sm border-b-2 border-wapify-border flex items-center justify-between bg-wapify-panel">
                        <span className="text-wapify-text">{selectedFile}</span>
                        <button
                          onClick={async () => {
                            if (!projectId) {
                              alert('Please save the project first')
                              return
                            }

                            try {
                              const updatedFiles = projectFiles.map(f =>
                                f.path === selectedFile ? { ...f, content: fileContent } : f
                              )
                              setProjectFiles(updatedFiles)

                              const userId = (session?.user as any)?.id || session?.user?.email
                              const response = await fetch(`/api/projects/${projectId}/files`, {
                                method: 'PUT',
                                headers: { 'Content-Type': 'application/json' },
                                body: JSON.stringify({ userId, files: updatedFiles })
                              })

                              if (response.ok) {
                                alert('✅ File saved!')
                                setLastSaved(new Date())

                                if (window.confirm('Rebuild the app to see changes?')) {
                                  await rebuildProject(projectId)
                                }
                              } else {
                                throw new Error('Save failed')
                              }
                            } catch (error) {
                              alert('❌ Error: ' + (error as Error).message)
                            }
                          }}
                          className="px-3 py-1 bg-wapify-accent text-white rounded-lg text-xs font-semibold hover:bg-wapify-accent-dark transition shadow-md"
                        >
                          💾 Save
                        </button>
                      </div>
                      <Editor
                        height="100%"
                        language={
                          selectedFile.endsWith('.tsx') || selectedFile.endsWith('.ts') ? 'typescript' :
                          selectedFile.endsWith('.jsx') || selectedFile.endsWith('.js') ? 'javascript' :
                          selectedFile.endsWith('.css') ? 'css' :
                          selectedFile.endsWith('.json') ? 'json' :
                          selectedFile.endsWith('.html') ? 'html' : 'plaintext'
                        }
                        theme="vs-dark"
                        value={fileContent}
                        onChange={(value) => setFileContent(value || '')}
                        options={{
                          minimap: { enabled: true },
                          fontSize: 14,
                          lineHeight: 22,
                          scrollBeyondLastLine: false,
                          automaticLayout: true,
                        }}
                      />
                    </>
                  ) : (
                    <div className="flex items-center justify-center h-full text-wapify-text-secondary">
                      <div className="text-center">
                        <div className="text-6xl mb-4">💻</div>
                        <p>Select a file to edit</p>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div className="w-full h-full flex items-center justify-center bg-wapify-bg p-8">
                <div className="max-w-4xl w-full">
                  <div className="text-center mb-8">
                    <svg className="w-24 h-24 mx-auto mb-4 text-wapify-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                    </svg>
                    <h2 className="text-3xl font-bold text-wapify-text mb-2">Dashboard</h2>
                    <p className="text-wapify-text-secondary">Coming soon - Monitor your app's performance and analytics</p>
                  </div>

                  <div className="grid md:grid-cols-3 gap-6">
                    <div className="bg-wapify-panel border-2 border-wapify-border rounded-2xl p-6 text-center">
                      <svg className="w-12 h-12 mx-auto mb-3 text-wapify-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                      </svg>
                      <h3 className="text-lg font-bold text-wapify-text mb-1">Deployments</h3>
                      <p className="text-2xl font-bold text-wapify-accent mb-2">-</p>
                      <p className="text-xs text-wapify-text-secondary">Total builds</p>
                    </div>

                    <div className="bg-wapify-panel border-2 border-wapify-border rounded-2xl p-6 text-center">
                      <svg className="w-12 h-12 mx-auto mb-3 text-wapify-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
                      </svg>
                      <h3 className="text-lg font-bold text-wapify-text mb-1">Users</h3>
                      <p className="text-2xl font-bold text-wapify-accent mb-2">-</p>
                      <p className="text-xs text-wapify-text-secondary">Active users</p>
                    </div>

                    <div className="bg-wapify-panel border-2 border-wapify-border rounded-2xl p-6 text-center">
                      <svg className="w-12 h-12 mx-auto mb-3 text-wapify-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                      </svg>
                      <h3 className="text-lg font-bold text-wapify-text mb-1">Performance</h3>
                      <p className="text-2xl font-bold text-wapify-accent mb-2">-</p>
                      <p className="text-xs text-wapify-text-secondary">Avg load time</p>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
