// Utilitaires pour valider et améliorer le code généré

export interface CodeValidation {
  isValid: boolean
  errors: string[]
  warnings: string[]
  suggestions: string[]
}

/**
 * Valide le code généré pour détecter des problèmes communs
 */
export function validateGeneratedCode(code: string, framework: 'html' | 'react' | 'vue'): CodeValidation {
  const errors: string[] = []
  const warnings: string[] = []
  const suggestions: string[] = []

  // Vérifications de base
  if (!code || code.trim().length === 0) {
    errors.push('Le code est vide')
    return { isValid: false, errors, warnings, suggestions }
  }

  if (code.length < 100) {
    warnings.push('Le code semble très court, peut-être incomplet')
  }

  // Vérification des APIs de storage interdites
  const storageAPIs = ['localStorage', 'sessionStorage', 'IndexedDB']
  for (const api of storageAPIs) {
    if (code.includes(api)) {
      errors.push(`Utilisation interdite de ${api} détectée`)
    }
  }

  // Vérifications spécifiques au framework
  switch (framework) {
    case 'html':
      validateHTML(code, errors, warnings, suggestions)
      break
    case 'react':
      validateReact(code, errors, warnings, suggestions)
      break
    case 'vue':
      validateVue(code, errors, warnings, suggestions)
      break
  }

  // Vérification de la palette Wapify
  if (!code.includes('#F5F3EF') && !code.includes('#CC785C')) {
    suggestions.push('Considérer l\'utilisation de la palette de couleurs Wapify')
  }

  // Vérification responsive
  if (!code.includes('viewport') && !code.includes('responsive') && !code.includes('mobile')) {
    suggestions.push('Ajouter des classes responsive pour mobile')
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
    suggestions
  }
}

function validateHTML(code: string, errors: string[], warnings: string[], suggestions: string[]) {
  // Vérifier structure HTML de base
  if (!code.includes('<!DOCTYPE') && !code.includes('<html')) {
    warnings.push('Structure HTML complète manquante')
  }

  // Vérifier meta viewport
  if (!code.includes('viewport')) {
    warnings.push('Meta viewport manquant pour le responsive')
  }

  // Vérifier présence de title
  if (!code.includes('<title>')) {
    suggestions.push('Ajouter une balise <title>')
  }

  // Vérifier les placeholders communs
  const placeholders = ['TODO', '...', 'placeholder', 'Lorem ipsum']
  for (const placeholder of placeholders) {
    if (code.toLowerCase().includes(placeholder.toLowerCase())) {
      warnings.push(`Placeholder "${placeholder}" détecté - code possiblement incomplet`)
    }
  }
}

function validateReact(code: string, errors: string[], warnings: string[], suggestions: string[]) {
  // Vérifier export default
  if (!code.includes('export default')) {
    errors.push('Export default manquant pour le composant React')
  }

  // Vérifier imports React
  if (code.includes('useState') && !code.includes("from 'react'") && !code.includes('from "react"')) {
    errors.push('Import React manquant pour les hooks')
  }

  // Vérifier fermeture des composants
  const openTags = (code.match(/</g) || []).length
  const closeTags = (code.match(/>/g) || []).length
  if (Math.abs(openTags - closeTags) > 5) {
    warnings.push('Déséquilibre possible dans les balises JSX')
  }

  // Vérifier les placeholders
  if (code.includes('// TODO') || code.includes('// Implementation')) {
    warnings.push('Code avec TODO détecté - possiblement incomplet')
  }

  // Suggestions
  if (!code.includes('TypeScript') && !code.includes('interface') && !code.includes('type ')) {
    suggestions.push('Considérer l\'ajout de types TypeScript')
  }
}

function validateVue(code: string, errors: string[], warnings: string[], suggestions: string[]) {
  // Vérifier structure Vue
  if (!code.includes('<template>')) {
    errors.push('Section <template> manquante')
  }

  if (!code.includes('<script')) {
    errors.push('Section <script> manquante')
  }

  // Vérifier Composition API
  if (code.includes('<script') && !code.includes('setup')) {
    suggestions.push('Considérer l\'utilisation de <script setup> (Composition API)')
  }

  // Vérifier imports Vue
  if ((code.includes('ref') || code.includes('reactive')) && !code.includes('from \'vue\'')) {
    errors.push('Import Vue manquant pour les refs/reactive')
  }
}

/**
 * Ajoute des métadonnées au code généré
 */
export function addCodeMetadata(code: string, metadata: {
  framework: string
  style: string
  generatedAt: string
  wapifyVersion: string
}): string {
  const comment = `
<!--
  Generated by Wapify AI
  Framework: ${metadata.framework}
  Style: ${metadata.style}
  Generated: ${metadata.generatedAt}
  Version: ${metadata.wapifyVersion}
  
  ⚠️ Do not use localStorage or sessionStorage in iframe context
-->
`
  
  // Insérer après la balise DOCTYPE ou au début
  if (code.includes('<!DOCTYPE')) {
    return code.replace('<!DOCTYPE', comment + '\n<!DOCTYPE')
  }
  
  return comment + code
}

/**
 * Nettoie le code généré (enlève les espaces superflus, etc.)
 */
export function cleanCode(code: string): string {
  return code
    .trim()
    // Enlever les lignes vides multiples
    .replace(/\n{3,}/g, '\n\n')
    // Normaliser les espaces
    .replace(/[ \t]+$/gm, '')
}

/**
 * Estime la complexité du code
 */
export function estimateComplexity(code: string): {
  lines: number
  characters: number
  complexity: 'simple' | 'medium' | 'complex'
  estimatedCredits: number
} {
  const lines = code.split('\n').length
  const characters = code.length
  
  let complexity: 'simple' | 'medium' | 'complex'
  let estimatedCredits: number
  
  if (lines < 100) {
    complexity = 'simple'
    estimatedCredits = 10
  } else if (lines < 300) {
    complexity = 'medium'
    estimatedCredits = 20
  } else {
    complexity = 'complex'
    estimatedCredits = 30
  }
  
  return {
    lines,
    characters,
    complexity,
    estimatedCredits
  }
}

/**
 * Vérifie si le code contient des données sensibles
 */
export function checkForSensitiveData(code: string): string[] {
  const sensitivePatterns = [
    { pattern: /api[_-]?key/gi, name: 'API Key' },
    { pattern: /password\s*[:=]\s*['"][^'"]+['"]/gi, name: 'Password' },
    { pattern: /secret/gi, name: 'Secret' },
    { pattern: /token\s*[:=]\s*['"][^'"]+['"]/gi, name: 'Token' },
  ]
  
  const found: string[] = []
  
  for (const { pattern, name } of sensitivePatterns) {
    if (pattern.test(code)) {
      found.push(name)
    }
  }
  
  return found
}

/**
 * Formate le code pour l'affichage (syntax highlighting basique)
 */
export function highlightSyntax(code: string): string {
  // Basique - pour un vrai highlighting, utiliser une lib comme Prism.js
  return code
    .replace(/(&lt;)([a-zA-Z][a-zA-Z0-9]*)/g, '$1<span class="tag">$2</span>')
    .replace(/(const|let|var|function|return|import|export)/g, '<span class="keyword">$1</span>')
}

/**
 * Extrait les dépendances du code (imports, CDN links, etc.)
 */
export function extractDependencies(code: string): {
  imports: string[]
  cdnLinks: string[]
  externalLibraries: string[]
} {
  const imports: string[] = []
  const cdnLinks: string[] = []
  const externalLibraries: string[] = []
  
  // Extraire les imports ES6
  const importMatches = code.matchAll(/import\s+.*\s+from\s+['"]([^'"]+)['"]/g)
  for (const match of importMatches) {
    imports.push(match[1])
  }
  
  // Extraire les liens CDN
  const cdnMatches = code.matchAll(/src=["'](https?:\/\/[^"']+)["']/g)
  for (const match of cdnMatches) {
    cdnLinks.push(match[1])
  }
  
  // Détecter les librairies externes utilisées
  const libraries = ['react', 'vue', 'tailwind', 'bootstrap', 'jquery']
  for (const lib of libraries) {
    if (code.toLowerCase().includes(lib)) {
      externalLibraries.push(lib)
    }
  }
  
  return {
    imports: [...new Set(imports)],
    cdnLinks: [...new Set(cdnLinks)],
    externalLibraries: [...new Set(externalLibraries)]
  }
}

/**
 * Génère un aperçu textuel du code pour l'utilisateur
 */
export function generateCodeSummary(code: string, framework: string): string {
  const { lines, characters, complexity } = estimateComplexity(code)
  const deps = extractDependencies(code)
  
  let summary = `📊 Résumé du code généré:\n\n`
  summary += `• Framework: ${framework}\n`
  summary += `• Lignes: ${lines}\n`
  summary += `• Caractères: ${characters}\n`
  summary += `• Complexité: ${complexity}\n`
  
  if (deps.imports.length > 0) {
    summary += `• Imports: ${deps.imports.length}\n`
  }
  
  if (deps.cdnLinks.length > 0) {
    summary += `• CDN: ${deps.cdnLinks.length} liens\n`
  }
  
  return summary
}

/**
 * Vérifie la compatibilité navigateur
 */
export function checkBrowserCompatibility(code: string): {
  compatible: boolean
  issues: string[]
  recommendations: string[]
} {
  const issues: string[] = []
  const recommendations: string[] = []
  
  // Vérifier les features modernes
  const modernFeatures = [
    { feature: 'optional chaining', pattern: /\?\./g },
    { feature: 'nullish coalescing', pattern: /\?\?/g },
    { feature: 'async/await', pattern: /async\s+function|await\s+/g },
  ]
  
  for (const { feature, pattern } of modernFeatures) {
    if (pattern.test(code)) {
      recommendations.push(`${feature} détecté - nécessite navigateurs modernes`)
    }
  }
  
  // Vérifier les APIs potentiellement non supportées
  if (code.includes('IntersectionObserver')) {
    recommendations.push('IntersectionObserver peut nécessiter un polyfill')
  }
  
  if (code.includes('fetch(')) {
    recommendations.push('Fetch API - supportée par tous les navigateurs modernes')
  }
  
  return {
    compatible: issues.length === 0,
    issues,
    recommendations
  }
}